//arabic translate
//need key of String and String value to show
Map<String, String> arabicLanguage = {
  //forget password
  "Password Reset Mail has been sent to your authorized Email":
      "تم إرسال بريد إعادة تعيين كلمة المرور إلى البريد الإلكتروني المعتمد الخاص بك",
  'Forget Password': 'نسيت كلمة المرور',
  "Please enter your email": "رجاء أدخل بريدك الإلكتروني",
  "We will send you a verify code to your\nemail":
      "سوف نرسل لك رمز التحقق إلى البريد الإلكتروني\n الخاص بك",
  "(Required)": "(مطلوب)",
  //login
  "Forget password?": "نسيت كلمة المرور؟",
  "Login successfully": "تم تسجيل الدخول بنجاح",
  'Login': 'تسجيل الدخول',
  "Password": "كلمة المرور",
  "Welcome Back": "مرحبًا بعودتك",
  "Please Log in To Continue": "الرجاء تسجيل الدخول للمتابعة",
  "Don't have an account ?": "ليس لديك حساب ؟",
  "Register now": "أنشئ حساب الأن",
  "User Is Deleted, Please contact Admin if you want to activate it":
      "تم حذف هذا الحساب قم بالتواصل مع الإدارة لاستعادته",
  "Invalid Credentials.": "مدخلات خاطئة",
  "User Not Found.": "لم يتم العثور على المستخدم.",
  "Email": "البريد الإلكتروني",
  "Account created successfully wait until accept it from administrator":
      "تم إنشاء الحساب بنجاح انتظر حتى يتم قبوله من الإدارة",
  "Your account not accepted yet wait until your account activate by admin":
      "لم يتم قبول حسابك بعد انتظر حتى يتم تفعيل حسابك بواسطة المشرف",

  //register
  "Job title": "العنوان المهني",
  "Cancel": "إلغاء",
  "Confirm": "تأكيد",
  "Select Date": "اختر تاريخاً",
  "Nation": "الجنسية",
  "Emirate": "الإمارة",
  "Gender": "الجنس",
  "Name according to passport": "الاسم حسب جواز السفر",
  "Current position and organization": "الوظيفة الحالية المؤسسة",
  "Academic qualification and specialization": "المؤهل الأكاديمي والتخصص",
  "Birthday date": "تاريخ الميلاد",
  'Personal image': "الصورة الشخصية",
  'Emirates ID photo': 'صورة الهوية الإماراتية',
  'Passport photo': 'صورة جواز السفر',
  'Press ID Image': 'صورة معرف الصحافة',
  "Name according to passport in English":
      "الاسم حسب جواز السفر باللغة الانجليزية",
  "Professional title": 'العنوان المهني',
  "website": "موقع إلكتروني",
  "mail box": "صندوق بريد",
  "Required fields": "الحقول الاجبارية",
  "UnRequired fields": "حقول غير اجبارية",
  'A copy of the last educational qualification':
      'نسخة من المؤهل التعليمي الأخير',
  "Fax": "فاكس",
  "New to our platform? Complete the details below.":
      "هل أنت جديد في منصتنا؟ أكمل التفاصيل أدناه.",
  'Select city': "اختر مدينة",
  "Driver": "سائق",
  "Station": "محطة",
  "Complete": "أكمل",
  "Back": "رجوع",
  "Tracking": "تتبع",
  'Select oil type': "اختر نوع الوقود",
  "Arabic name": "الاسم بالعربية",
  "English name": "الاسم بالانجليزية",
  "Car number": "رقم السيارة",
  "Mobile number": "رقم الهاتف المحمول",
  "Confirm password": "تأكيد كلمة المرور",
  "Account created successfully please login ":
      "تم إنشاء الحساب بنجاح يرجى تسجيل الدخول",
  'Account created successfully': "تم إنشاء الحساب بنجاح",
  "Account created successfully wait until accept it from adminstrator":
      "تم إنشاء الحساب بنجاح انتظر حتى يتم قبوله من الإدارة",
  'Register': 'إنشاء حساب',
  "Create account": 'إنشاء حساب',
  '(Optional)': '(اختياري)',
  'Upload Image': 'ارفع الصورة',
  "Replace Image": "استبدال الصورة",
  "Delete Image": "حذف الصورة",
  "View Full Image": "عرض الصورة كاملة",
  "Add location": "اضف موقع",
  "Male": "ذكر",
  "Female": "انثى",
  "Fill all required filed": "املأ جميع الحقول المطلوبة",
  'Member': "عضو",
  "Guest": "زائر",
  'Please enter one capital letter at less': "ادخل حرف كبير واحد على الاقل",
  'Please enter one number at less': "ادخل رقم واحد على الاقل",
  'Please enter one lower letter at less': "ادخل حرف صغير واحد على الاقل",
  "Qualifications": "المؤهل العلمي",
  "Job type": "المهنة",
  "Member type": "نوع العضوية",
  "Worker": "عامل",
  "Affiliate": "منتسب",
  "Message from employer to whom it may concern":
      "رسالة لمن يهمه الأمر من جهة العمل",
  "City": "المدينة",
  'Emirates ID photo front face': "الهوية الاماراتية الوجه الأمامي",
  'Emirates ID photo back face': "الهوية الاماراتية الوجه الخلفي",
  'A copy of the passport with the family book for citizens':
      "صورة من جواز السفر مع خلاصة القيد للمواطنين",
  "A copy of the passport with a valid residence permit for expatriates":
      "صورة من جواز السفر مع إقامة سارية المفعول للوافدين",
  //helper
  "Failed to lunch": "فشل في التشغيل",
  'Please enter a valid name': 'رجاء ادخل اسما صحيحا',
  'Please enter a valid email': 'يرجى إدخال بريد إلكتروني صحيح',
  'Please enter a valid phone number': 'يرجى إدخال رقم هاتف صالح',
  "This field is required": "هذا الحقل مطلوب",
  "Can't be less than": "لا يمكن أن يكون أقل من",
  "Can't be more than": "لا يمكن أن يكون أكثر من",
  "Doesn't compare": "لا يوجد تطابق",
  "Failed to pick image": "لم يتم اختيار صورة",
  //Dio errors
  'Not Found': "السيرفر قيد الصيانة حاليا يرجى الانتظار",
  "No internet connection": "لا يوجد اتصال بالانترنت",
  "TimeOut for the request": "انتهت مهلة الطلب",
  'Something went wrong': 'حدث شيئ ما خاطئ',
  'Retry': 'أعد المحاولة',
  'Server error': 'هنالك خطأ في السيرفر يرجى الإنتظار لإصلاح الخطأ',
  'Bad response incorrect input': 'استجابة سيئة تأكد من إدخال مدخلات صحيحة',
  "Continue offline ?": "استمر بدون اتصال ؟",
  'Receive connection timeout': 'انتهت مهلة الاستجابة',
  'Something went wrong try again': 'هنالك شي ما خاطى اعد المحاولة',
  "Un know error": "خطأ غير معروف",
  'Request connection timeout': 'انتهت مهلة الاتصال',
  "Un authorized": "غير مصرح لك بالوصول",
  //search
  'Search...': "بحث...",
  'Search': 'البحث',
  "Filter by": "تصنيف حسب",
  //orders
  "Current": "الحالية",
  "Completed": "المكتملة",
  "Payment way": "وسيلة الدفع",
  "Total": "المجموع",
  "Status": "الحالة",
  "Date": "التاريخ",
  "Cancel order": "إلغاء الطلب",
  "Show details": "عرض التفاصيل",
  "Login to access this page": "قم بتسجيل الدخول للوصول إلى هذه الصفحة",
  "Go to login": "قم بتسجيل الدخول",
  //profile
  'Edit Profile': 'تعديل الحساب',
  'Points': 'النقاط',
  "profile": "حسابي",
  "Save": "حفظ",
  'Delete Account': 'حذف الحساب',
  'Log Out': 'تسجيل الخروج',
  "Logout successfully": "تم تسجيل الخروج بنجاح",
  "Account Deleted successfully": "تم حذف الحساب بنجاح",
  "Yes": "نعم",
  "No": "لا",
  "Are you sure you want to delete this account ?":
      " هل أنت متأكد أنك تريد حذف الحساب ؟ ",
  'Contact us': 'اتصل بنا',
  'Privacy policy': 'سياسة الخصوصية',
  'About us': 'من نحن',
  'Terms & Conditions': 'الشروط والاحكام',
  'Addresses': "العناوين",
  'Change Password': "تغيير كلمة المرور",
  'Membership renewal': "تجديد اشتراك العضوية",
  'Solidarity Fund': "صندوق التكافل",
  'Loans': "القروض",
  "Are you sure you want to renewal your membership ?":
      "هل أنت متأكد انك تريد تجديد اشتراك العضوية ؟",
  "Requested successfully": "تم الطلب بنجاح",
  "Deleted successfully": "تم الحذف بنجاح",
  "Are you sure you want to delete this account ? please enter your password first for complete process.":
      "هل أنت متأكد أنك تريد حذف هذا الحساب؟ الرجاء إدخال كلمة المرور أولاً لإكمال العملية.",
  //change password
  "Change password": "تغيير كلمة المرور",
  "Current password": "كلمة المرور الحالية",
  "New password": "كلمة المرور الجديدة",
  "Please fill all field to change your password":
      "قم بملأ جميع الحقول لتغيير كلمة المرور الخاصة بك",
  "Password Changed": "تم تغيير كلمة المرور",
  "Update": "تعديل",
  //static pages
  'Contact Us': 'اتصل بنا',
  'Privacy Policy': 'سياسة الخصوصية',
  "Message send successfully": "تم إرسال الرسالة بنجاح",
  "Write your message": "اكتب رسالتك",
  'write your message her': 'اكتب رسالتك هنا',
  'Send': 'إرسال',
  'Title': "عنوان الرسالة",
  "Website": "الموقع",
  //Notifications
  "Notifications": "الإشعارات",
  "No notifications to show": "لا يوجد اشعارات لعرضها",
  //Home
  'Reservations': "الحجوزات",  
   'Reservations ': " الحجوزات والاشتراكات",
  "Events": "الفعاليات",
  "Home": "الصفحة الرئيسية",
  "Reservation": "الحجز",
  "The session has expired. Log in again":
      "انتهت صلاحية الجلسة قم بتسجيل الدخول",
  'Hotel offers and discounts': "عروض وخصومات الفنادق",
  'Honor Council': "مجلس الشرف",
  'Association News': "اخبار الجمعية",
  "About the Association": "عن الجمعية",
  "Main System": "النظام الاساسي",
  "Advertising decision": "قرار الاشهار",
  "Board of Directors": "مجلس الادارة",
  "Local Board of Directors": "مجلس الادارة المحلي",
  "Current Board of Directors": "مجلس الادارة الحالي",
  "Previous Councils": "المجالس السابقة",
  "Previous boards of directors": "مجالس الادارة السابقة",
  "Journalists' unions and associations": "نقابات وجمعيات الصحفيين",
  "International unions": "النقابات الدولية",
  "Arab Journalists Associations and Syndicates":
      "جمعيات ونقابات الصحفيين العرب",
  "Laws": "القوانين",
  "Event number": "عدد الفعاليات",
  "Friendly sites": "مواقع صديقة",
  "Journalistic Code of Honor": "ميثاق الشرف الصحفي",
  "Press and Publications Law": "قانون المطبوعات والنشر",
  "Media Activities Bill": "مشروع قانون الأنشطة الإعلامية",
  "Public Benefit Associations Law": "قانون الجمعيات ذات النفع العام",
  "Association Membership": "عضوية الجمعية",
  "Arab Journalists Union": "اتحاد الصحفيين العرب",
  "Associations and unions of Arab journalists":
      "جمعيات ونقابات الصحفيين العرب",
  "International Federation of Journalists": "الاتحاد الدولي للصحفيين",
  "About the Solidarity Fund Membership": "حول عضوية صندوق التكافل",
  "Media Center": "المركز الاعلامي",
  "Media news": "اخبار الاعلام",
  "Photo Gallery": "البوم الصور",
  "Video Gallery": "البوم الفيديو",
  "Sponsors": "الرعاة",
  "Initiatives and events": "المبادرات والفعاليات",
  "Journalists from the beautiful era": "صحفيون من العصر الجميل",
  "Journalists' Unions and Association": "نقابات وجمعيات الصحفيين",
  "News": "أخبار",
  "Members number": "عدد الاعضاء",
  "Events number": "عدد الأحداث",
  "Since": "منذُ",
  'minutes': "دقائق",
  "Read more": "اقرأ المزيد",
  "views": "مشاهدات",
  'Profile': "حساب العضو",
  "Attachment": "المرفقات",
  "Download file": "تحميل الملف",
  //solidarity_fund
  'to access this page':"للوصول لمحتويات هذه الصفحة",
  'Your request has been denied,': "لقد تم رفض طلبك ،",
  "Your application for subscription to the Solidarity Fund has been submitted and is under review.":
      "لقد تم تقديم طلبك بالاشتراك بصندوق التكافل وهو في حالة التدقيق",
  "To subscribe to the Solidarity Fund, enter the end date of the subscription to the Fund and send the application , notice that Subscription Fee is":
      "للإشتراك في صندوق التكافل أدخل تاريخ إنتهاء الإشتراك في الصندوق وأرسل الطلب مع العلم أن رسوم الإشتراك هي",
  "Submit": "ارسال",
  "End Subscription date": "تاريخ انتهاء الاشتراك",
  "You have successfully subscribed. Wait for the administration to accept it":
      "تم الاشتراك بنجاح انتظر حتى يتم القبول من الادارة",
  "Already subscribed": "لديك طلب مسبق",
  "You are a member of the Solidarity Fund. Now you can request a loan and monitor loan payments.":
      "أنت مشترك بصندوق التكافل الأن يمكنك طلب قرض ومراقبة دفعات القروض",
  "To subscribe to the Solidarity Fund, you need to register as a member":
      "للاشتراك بصندوق التكافل يجب ان تقوم بانشاء حساب عضو",
  //loan
  "Loan amount": "مبلغ القرض",
  "Number of payment months": "عدد اشهر التسديد",
  "Pending": "بانتظار القبول",
  "See Loan payments": "مشاهدة دفعات القرض",
  "Accepted": "تم قبولها",
  "Rejected": "تم رفضها",
  'Refused': "تم رفضها",
  "See loans": "مشاهدة القروض",
  "Not Sunbscribed in Solidarity Fund OR your Request Still Pending":
      "لم يتم الاشتراك في صندوق التكافل أو طلبك لا يزال معلقًا",
  //loan details
  "Payment amount": "المبلغ المدفوع",
  "Total payment amount": "مبلغ الدفع الإجمالي",
  "Remaining": "المبلغ المتبقي",
  'Loan payments': "دفعات القرض",
  "To request a loan, you need to register as a member":
      "لطلب قرض يجب ان تقوم بإنشاء حساب عضو",
  //add loan
  "Fill in all fields to apply for the loan. It should be noted that the loan is repaid in installments over 24 months.":
      "قم بملء جميع الحقول لطلب القرض، يجب ملاحظة أن القرض يسدد على دفعات لمدة 24 شهرًا",
  "Request a loan": "اطلب قرضاً",
  'ID photo': "صورة شخصية",
  'Salary slip': "قسيمة الراتب",
  "Loan requested successfully wait for approve it":
      "تم طلب القرض بنجاح بانتظار الموافقة عليه",
  "No Data to show": "لا يوجد بيانات لعرضها",
  "Letter of commitment from the employer": "رسالة تعهد من جهة العمل",
  "Value of each installment": "قيمة كل قسط",
  "Last installment value": "قيمة القسط الأخير",
  "Not Sunbscribed in Solidarity Fund": "عليك الاشتراك بصندوق التكافل لطلب قرض",
  "Wrong entry for loan info": "إدخال خاطئ لمعلومات القرض",
  //admin meeting
  "Admin meeting": "اجتماع مجلس الإدارة",
  'Description': "الوصف",
  //halls
  "Dirham": "درهم",
  "Start Date": "تاريخ البدء",
  "End Date": "تاريخ الانتهاء",
  "End of subscription": "تاريخ انتهاء الاشتراك",
  "Princedom": "الامارة",
  "Price": "السعر",
  "Discount price": "السعر بعد الحسم",
  "Exhibition": "المعارض",
  "Free": "مجاني",
  "Subscribe": "اشتراك",
  "Halls": "القاعات",
  "Theater": "مسرح",
  "Reserve": "حجز",
  "Type": "النوع",
  "Number": "الرقم",
  "Capacity": "السعة",
  "Floor": "الطابق",
  "Available": "متاح",
  "Un Available": "غير متاح",
  "Another Reservation was Found": "هذه القاعة محجوزة في هذا التاريخ",
  "Already subscribe Request was found": "لديك طلب اشتراك مسبق",
  "Subscription time is end": "انتهى تاريخ الاشتراك",
  "Discount": "نسبة الخصم",
  //edit guest
  "Updated successfully": "تم التعديل بنجاح",
  "Edit profile": "تعديل الحساب",
  //Courses
  "Courses": "دورات",
  //Seminars
  "Seminars": "ندوات",
  //"Reservations"
  "Subscriptions": "الاشتراكات",
  "Hall ": "القاعة",
  "Hall": "قاعة",
  "Event": "الفعالية",
  "Daily fees": "الرسوم اليومية",
  //Membership status
  "Membership status": "حالة العضوية",
  "Submit an application": "تقديم طلب",
  "Membership renewal fees": "رسوم تجديد العضوية",
  "General Union Membership Application Fees": "رسوم طلب عضوية الاتحاد العام",
  "International Federation Membership Application Fee":
      "رسوم طلب عضوية الاتحاد الدولي",
  "Not active": "غير فعال",
  "Active": "فعال",
  "Renewal of membership in the Journalists Association":
      "تجديد العضوية في جمعية الصحفيين",
  "Arab Journalists Union Subscription": "إشتراك اتحاد الصحفيين العرب",
  "Subscribe to the International Federation of Journalists":
      "اشترك في الاتحاد الدولي للصحفيين",
};
