//english translate
//need key of String and String value to show

Map<String, String> englishLanguage = {
  //forget password
  "Password Reset Mail has been sent to your authorized Email":
      "Password Reset Mail has been sent to your authorized Email",
  'Forget Password': 'Forget Password',
  "Please enter your email": "Please enter your email",
  "We will send you a verify code to your\nemail":
      "We will send you a verify code to your\nemail",
  "(Required)": "(Required)",
  //login
  "Forget password?": "Forget password?",
  "Login successfully": "Login successfully",
  'Login': 'Login',
  "Password": "Password",
  "Welcome Back": "Welcome Back",
  "Please Log in To Continue": "Please Log in To Continue",
  "Don't have an account ?": "Don't have an account ?",
  "Register now": "Register now",
  "This account has been deleted. Contact the administration to restore it":
      "This account has been deleted. Contact the administration to restore it",
  "Invalid Credentials.": "Invalid Credentials.",
  "User Not Found.": "User Not Found.",
  //register
  "New to our platform? Complete the details below.":
      "New to our platform? Complete the details below.",
  'Select city': 'Select city',
  "Driver": "Driver",
  "Station": "Station",
  'Select oil type': 'Select oil type',
  "Tracking": "Tracking",
  "Back": "Back",
  "Account created successfully please login ":
      "Account created successfully please login ",
  'Register': 'Register',
  "Create account": "Create account",
  "Arabic name": "Arabic name",
  "English name": "English name",
  "Mobile number": "Mobile number",
  "Car number": "Car number",
  "Confirm password": "Confirm password",
  '(Optional)': '(Optional)',
  'Upload Image (Optional)': 'Upload Image (Optional)',
  "Replace Image": "Replace Image",
  "Delete Image": "Delete Image",
  "View Full Image": "View Full Image",
  "Add location": "Add location",
  "Complete": "Complete",
  //helper
  "Failed to lunch": "Failed to lunch",
  'Please enter a valid name': 'Please enter a valid name',
  'Please enter a valid email': 'Please enter a valid email',
  'Please enter a valid phone number': 'Please enter a valid phone number',
  "This field is required": "This field is required",
  "Can't be less than": "Can't be less than",
  "Can't be more than": "Can't be more than",
  "Doesn't compare": "Doesn't compare",
  "Failed to pick image": "Failed to pick image",
  //Dio errors
  "No internet connection": "No internet connection",
  "TimeOut for the request": "TimeOut for the request",
  'Something went wrong': 'Something went wrong',
  'Retry': 'Retry',
  'Server error': 'Server error',
  'Bad response incorrect input': 'Bad response incorrect input',
  "Continue offline ?": "Continue offline ?",
  'Receive connection timeout': 'Receive connection timeout',
  'Something went wrong try again': 'Something went wrong try again',
  "Un know error": "Un know error",
  'Request connection timeout': 'Request connection timeout',
  "Un authorized": "Un authorized",
  //Home
  'Good Morning': 'Good Morning',
  'Good Afternoon': 'Good Afternoon',
  'Good Evening': 'Good Evening',
  "Special Restaurants": "Special Restaurants",
  "All Restaurants": "All Restaurants",
  'Search...': 'Search...',
  "Home": "Home",
  "Orders": "Orders",
  "Profile": "Profile",
  'Hello': 'Hello',
  "Meals": "Meals",
  "The session has expired. Log in again":
      "The session has expired. Log in again",
  //search
  'Search': 'Search',
  "Filter by": "Filter by",
  "Products": "Products",
  "Restaurants": "Restaurants",
  //orders
  "Current": "Current",
  "Completed": "Completed",
  "Payment way": "Payment way",
  "Total": "Total",
  "Status": "Status",
  "Date": "Date",
  "Cancel order": "Cancel order",
  "Show details": "Show details",
  //product_details
  "Restaurant": "Restaurant",
  "Category": "Category",
  'In Stock,': 'In Stock,',
  'Not In Stock,': 'Not In Stock,',
  'Description': 'Description',
  'Related Products': 'Related Products',
  "Add to cart": "Add to cart",
  "Update Quantity": "Update Quantity",
  "Remove from cart": "Remove from cart",
  "Added successfully": "Added successfully",
  "You can only request food from the same restaurant":
      "You can only request food from the same restaurant",
  "Removed successfully": "Removed successfully",
  "Updated successfully": "Updated successfully",
  "Additional notes": "Additional notes",
  "Tell us about it": "Tell us about it",
  //cart
  "Total Price ": "Total Price ",
  'Checkout': 'Checkout',
  "Cart": "Cart",
  "Cart Is Empty": "Cart Is Empty",
  "Deleted successfully": "Deleted successfully",
  //checkout
  'Payment Methods': 'Payment Methods',
  'cash': 'cash',
  'Payment Card': 'Payment Card',
  'Select time': 'Select time',
  'Order for now': 'Order for now',
  'Add date for the  order': 'Add date for the  order',
  "Choose Date": "Choose Date",
  "Choose Time": "Choose Time",
  'Choose address': 'Choose address',
  "Place order": "Place order",
  'Dinar': 'Dinar',
  "Payment card isn't available for now":
      "Payment card isn't available for now",
  "You need to add products before order":
      "You need to add products before order",
  "Order placed successfully": "Order placed successfully",
  "Please add address": "Please add address",
  "Add address": "Add address",
  //order details
  "Order Details": "Order Details",
  'Quantity :': 'Quantity :',
  'Order number ': 'Order number ',
  'Price After Discount ': 'Price After Discount ',
  'Currency ': 'Currency ',
  'Date ': 'Date ',
  'Coupon code ': 'Coupon code ',
  'Payment method ': 'Payment method ',
  'Coupon Discount ': 'Coupon Discount ',
  //orders
  "Order : ": "Order : ",
  "pending": "Pending",
  "Payment way : ": "Payment way : ",
  "Total : ": "Total : ",
  "Product Orders": "Product Orders",
  "Services Orders": "Services Orders",
  "ServicesProvider : ": "ServicesProvider : ",
  "Company Name : ": "Company Name : ",
  "Driver Name : ": "Driver Name : ",
  "Status : ": "Status : ",
  'Pending': "Pending",
  "Login to access this page": "Login to access this page",
  "Go to login": "Go to login",
  "Are you sure you want to cancel this order ?":
      "Are you sure you want to cancel this order ?",
  //order tracking
  "Order Tracking": "Order Tracking",
  "Ordered": "Ordered",
  "Processing": "Processing",
  "Charged": "Charged",
  "Accepted": "Accepted",
  "Wait until tracking is added to the order by the administration":
      "Wait until tracking is added to the order by the administration",
  //profile
  'Edit Profile': 'Edit Profile',
  'Points': 'Points',
  'Delete Account': 'Delete Account',
  'Log Out': 'Log Out',
  "Logout successfully": "Logout successfully",
  "Account Deleted successfully": "Account Deleted successfully",
  "Yes": "Yes",
  "No": "No",
  "Are you sure you want to delete this account ?":
      "Are you sure you want to delete this account ?",
  'Contact us': 'Contact us',
  'Privacy policy': 'Privacy policy',
  'About us': 'About us',
  'Terms & Conditions': 'Terms & Conditions',
  'Addresses': 'Addresses',
  'Change Password': 'Change Password',
  //change password
  "Change password": "Change password",
  "Current password": "Current password*",
  "New password": "New password",
  "Please fill all field to change your password":
      "Please fill all field to change your password",
  "Password Changed": "Password Changed",
  "Update": "Update",
  //static pages
  'Contact Us': 'Contact Us',
  'Privacy Policy': 'Privacy Policy',
  "Message send successfully": "Message send successfully",
  "Write your message": "Write your message",
  'write your message her': 'write your message her',
  'Send': 'Send',
  'Title': 'Title',
  //Notifications
  "Notifications": "Notifications",
  "No notifications to show": "No notifications to show",
  //addresses
  'Name': 'Name',
  "Edit": "Edit",
  "Add": "Add",

};
